### ISSUE TITLE
Serviço retorna erro para índices do servidor basalto01

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/previousTerm#3]
@heitorbarbieri,

Foi identificado que na busca avançada do índice COVID a funcionalidade de navegação nos termos do índice não estava funcionando, ao realizar o debug identifiquei que o serviço Previousterm esta retornando o erro abaixo  para qualquer execução/índice do servidor basalto01 (índices lucene 3.6) mas esta retornando resultado para a instalação no servidor basalto02 (portal - índice lucene 5).

```
javax.servlet.ServletException: java.lang.NumberFormatException: For input string: "pv.gz"
	br.bireme.prvtrm.PreviousTermServlet.init(PreviousTermServlet.java:85)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:849)
	org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583)
	org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:454)
	java.lang.Thread.run(Thread.java:722)

```

Exemplo de chamada:

http://basalto01.bireme.br:8981/previousterm/PreviousTermServlet?index=covidoms&fields=tw&init=covid&maxTerms=200&direction=next

**Comment by renatomurasaki** [comment]
@heitorbarbieri, por favor, verificar o que ocorre neste caso.

**Comment by viniciusandrade** [comment]
@heitorbarbieri favor informar se é possível e viável a leitura do índice covid-oms (lucene 3.6) na versão atual do PreviousTerm ou se devemos retirar o link de browse do índice da interface. 

Obrigado

**Comment by heitorbarbieri** [comment]
@viniciusandrade,

Por favor, teste a versão atual. Repare que houve um pequena alteração na url de previousTerm para previousTerm_L3 . Veja exemplo abaixo:

http://basalto01.bireme.br:8180/previousTerm_L3/PreviousTermServlet?index=covidoms&fields=tw&init=covid&maxTerms=200&direction=next

Note que ainda não foi realizado o processo de limpeza dos termos do índice conforme havíamos conversado (issue: https://github.com/bireme/previousTerm/issues/4)

**Comment by viniciusandrade** [comment]
@heitorbarbieri OK, url do serviço configurado e executando corretamente para a base WHO COVID.

Obrigado
